name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Build Docker image
        run: |
          docker build -t flaskapp .

      - name: Push Docker image to Docker Hub
        if: success()  # Pousser uniquement si les tests passent
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker tag flaskapp $DOCKER_USERNAME/flaskapp:latest
          docker push $DOCKER_USERNAME/flaskapp:latest

      - name: Push image to additional registry
        if: success()
        run: |
          docker tag flaskapp registry.example.com/username/flaskapp:latest
          docker push registry.example.com/username/flaskapp:latest

      - name: Send notification on test failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.example.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'CI Pipeline - Test Failure'
          body: 'Un test a échoué dans le workflow CI.'
          to: 'ton.email@example.com'
          from: 'ci-notifier@example.com'
